# Generated by Django 2.2.6 on 2019-10-24 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
