# Generated by Django 2.2.6 on 2019-10-24 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
