# Generated by Django 2.2.6 on 2019-10-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20191024_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_temp_unit',
            field=models.CharField(choices=[('Fahrenheit', 'Fahrenheit'), ('Celsius', 'Celsius')], default='Fahrenheit', max_length=11),
        ),
    ]
