# Generated by Django 2.2.6 on 2019-10-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_cook_temp_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.CharField(default='', max_length=300),
        ),
    ]
