# Generated by Django 2.2.6 on 2019-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
