# Generated by Django 2.2.6 on 2019-10-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20191024_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.CharField(blank=True, default=' ', max_length=300),
        ),
    ]
