# Generated by Django 2.2.6 on 2019-10-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191024_0901'),
        ('recipes', '0009_auto_20191024_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_favorites',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
